name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: tinygo/tinygo-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: TinyGo version check
        run: tinygo version